# Generated by Django 5.2.6 on 2025-11-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_comunidade_topico_respostatopico'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='spoiler',
            field=models.BooleanField(default=False, verbose_name='Contém Spoiler'),
        ),
    ]
