# Generated by Django 5.2.6 on 2025-11-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_comentario_spoiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='trailer',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
